import openai
import re


#api request instructions
def spice_to_recipe(prompt, openapi_key):
    openai.api_key = openapi_key
    response = openai.Completion.create(
        engine = 'text-davinci-003',
        prompt = prompt,
        max_tokens = 128,
        temperature = 0.5,
        n = 1,
        stop = None
    )

    #index selection of the responses generated by ChatGPT; choosing the first one
    if response.choices:
        lines = response.choices[0].text.split('\n')
        lines[0] = lines[0].replace(', and',',')
        lines[1] = lines[1].replace(', and',',')
        lines[0] = lines[0].replace(',',' +')
        lines[1] = lines[1].replace(',',' +')
        return '\n'.join(lines)
    else:
        return None
