import openai
import re

def to_prompt(spices):
    s = ', '.join(spices)
    return f'Please make a recipe from the following list of ingredients: {s}'

def parse_recipe(recipe, spices):
    # Remove instructions and newlines
    recipe = re.sub(r'Instructions(.|\n)*', '', recipe, re.I)
    recipe = re.sub(r".*Ingredients.*", '', recipe,  re.I)
    lines = re.sub(r"\n+", '\n', recipe).split('\n')
    (added, title, *ingredients) = lines
    # Extract list of ingredients
    ingredients = [
        re.sub(r'^- ?', '', item) for item in ingredients
    ]
    # Combine list of parsed spices with prompt
    added_spices = re.split('\s*,\s*', added)
    spices = spices + added_spices
    # Remove empty items from lists
    ingredients = [re.sub('\s+', ' ', s).strip() for s in ingredients]
    ingredients = [s for s in ingredients if len(s) > 3]
    spices = [re.sub('\s+', ' ', s).strip() for s in spices]
    spices = [s for s in spices if len(s) > 3]
    # Pre-format example display of recipe
    text = (
        f"Title: {title}\n"
        f"Spices: {', '.join(spices)}\n"
        f"Ingredients: {', '.join(ingredients)}"
    )
    return {
        "ingredients": ingredients,
        "spices": spices,
        "title": title,
        "text": text
    }

#api request instructions
def spice_to_recipe(spices, openapi_key):

    openai.api_key = openapi_key
    response = openai.Completion.create(
        prompt = to_prompt(spices),
        engine = 'text-davinci-003',
        max_tokens = 128,
        temperature = 0.5,
        n = 1,
        stop = None
    )

    #index selection of the responses generated by ChatGPT; choosing the first one
    if response.choices:
        lines = response.choices[0].text.split('\n')
        lines[0] = lines[0].replace(', and',',')
        lines[0] = lines[0].replace('+',',')
        recipe = '\n'.join(lines)
        return parse_recipe(recipe, spices)
    else:
        return None
